[package]
name = "pewpewpew"
version = "0.0.1"
description = "Runs lots of benches (pews, geddit?)"
license = "CAL-1.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://github.com/holochain/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

[dependencies]
actix-web = "2"
actix-http = "1"
actix-service = "1"
actix-rt = "1"
actix = "0.9"
once_cell = "1"
serde = "1"
futures = "0.3"
thiserror = "1"
hex = "0.4"
serde_json = "1"
ring = "0.16"
base64 = "0.12"

[workspace]
